# -*- coding: utf-8 -*-
"""Sport_Management_System_for_Injury_and_fatigue_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRFQ3gUPhH5TqD7MG3iKc0d5VavzURMG

# 🏥⚽ Sport Management System for Injury and Fatigue Detection

A **Sport Management System for Injury and Fatigue Detection** is an intelligent platform designed to monitor athletes’ physical condition and predict potential injury risks before they occur. In modern sports environments, athletes are exposed to intense training loads, competitive pressure, and tight schedules. Without proper monitoring, accumulated fatigue can significantly increase the probability of injury. This system combines wearable technology, data analytics, and machine learning to support data-driven decision-making in sports management.

---

## 🎯 System Objectives

The main goal of this system is to improve athlete safety and performance. Specifically, it aims to:

* Monitor athlete physiological and performance data
* Detect early signs of fatigue
* Predict injury risk using machine learning models
* Provide alerts and recommendations to coaches and medical staff
* Optimize training load and recovery management

By achieving these objectives, teams can reduce injuries and maintain consistent performance levels.

---

## 📊 Data Collection and Inputs

The system relies on multiple data sources to ensure accurate predictions. These include:

* **Physiological data**: heart rate, heart rate variability (HRV), sleep duration
* **Performance data**: speed, acceleration, distance covered, training intensity
* **Medical history**: previous injuries, recovery time
* **Self-reported data**: fatigue levels, muscle soreness, stress

By analyzing patterns across these variables, the system identifies abnormal trends that may indicate elevated injury risk.

---

## 🤖 Role of Machine Learning

Machine learning models are used to classify athletes as either **high-risk** or **low-risk** for injury. Common algorithms include:

* **K-Nearest Neighbors (KNN)** – identifies risk based on similarity to other athletes
* **Support Vector Machine (SVM)** – effective for complex classification boundaries
* **Decision Tree** – provides interpretable decision rules

Model performance is evaluated using:

* Accuracy
* Precision
* Recall (especially important for detecting injured athletes)
* F1-score
* AUC

Among these, recall is particularly critical because failing to detect a high-risk athlete may result in serious injury.

---

## ✅ Benefits of the System

Implementing this system offers several advantages:

* Early injury prevention
* Improved workload management
* Reduced medical costs
* Data-driven coaching decisions
* Enhanced athlete longevity

This proactive approach shifts sports management from reactive treatment to preventive care.

---

## ⚠ Challenges

Despite its advantages, the system faces certain challenges:

* Imbalanced datasets (fewer injury cases)
* Sensor inaccuracies
* Privacy and data security concerns
* Risk of model overfitting

Addressing these challenges is essential for reliable real-world implementation.

---

## 📌 Conclusion

A Sport Management System for Injury and Fatigue Detection represents a significant advancement in modern sports analytics. By integrating wearable data, historical records, and machine learning techniques, the system enables early detection of fatigue and injury risk. This ultimately protects athletes, enhances performance, and supports smarter sports management decisions.

## **PREIMINARY STAGES OF MACHINE LEARNING**

### **Load the Necessay Libraries for Data Importation and Manipulation**

#
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### **Import the Data from the Local Directory**"""

uploaded = files.upload()

"""### **Read the Data as a Data Frame**"""

df = pd.read_csv("sports_data.csv")
df.head()

"""#### **Variables Definition and their Measurement**"""

from IPython.display import HTML

# Prepare lists to store variable information
variable_names = []
data_types = []
definitions = []
measurements = []
other_info = []

# Define descriptions for each column (based on common sports science context)
column_descriptions = {
    'athlete_id': ('Unique identifier for each athlete.', 'ID', ''),
    'session_id': ('Unique identifier for each training session.', 'ID', ''),
    'date': ('Date of the training session.', 'Date', ''),
    'session_type': ('Type of session (e.g., training, match).', 'Categorical', ''),
    'total_distance': ('Total distance covered during the session.', 'Meters (m)', ''),
    'high_speed_running': ('Distance covered at high speed during the session.', 'Meters (m)', ''),
    'sprint_count': ('Number of sprints performed.', 'Count', ''),
    'accelerations': ('Number of accelerations during the session.', 'Count', ''),
    'decelerations': ('Number of decelerations during the session.', 'Count', ''),
    'player_load': ('An aggregate measure of external load on the athlete.', 'Arbitrary Unit', ''),
    'wellness_score': ("Athlete's self-reported wellness status.", 'Ordinal Scale (e.g., 1-5)', ''),
    'rpe': ('Rate of Perceived Exertion for the session.', 'Ordinal Scale (e.g., 1-10)', ''),
    'training_duration': ('Duration of the training session.', 'Minutes', ''),
    'sleep_quality': ("Athlete's self-reported sleep quality.", 'Ordinal Scale (e.g., 1-5)', ''),
    'stress_level': ("Athlete's self-reported stress level.", 'Ordinal Scale (e.g., 1-5)', ''),
    'mood_score': ("Athlete's self-reported mood status.", 'Ordinal Scale (e.g., 1-5)', ''),
    'muscle_soreness': ("Athlete's self-reported muscle soreness level.", 'Ordinal Scale (e.g., 1-5)', ''),
    'acute_workload': ('Short-term training load, typically 7 days.', 'Arbitrary Unit', ''),
    'chronic_workload': ('Long-term training load, typically 28 days.', 'Arbitrary Unit', ''),
    'acwr': ('Acute:Chronic Workload Ratio, indicating training load balance.', 'Ratio', ''),
    'prior_injury': ('Binary indicator for whether the athlete had a prior injury.', 'Binary (0=No, 1=Yes)', ''),
    'match_congestion': ('Binary indicator for high match frequency or congestion.', 'Binary (0=No, 1=Yes)', ''),
    'position': ("Athlete's playing position.", 'Categorical', ''),
    'sport_specific_actions': ('Count of sport-specific actions performed.', 'Count', ''),
    'fatigue_level': ("Athlete's self-reported fatigue level.", 'Ordinal Scale (e.g., 1-5)', ''),
    'injury_7d': ('Outcome variable: whether an injury occurred within 7 days post-session.', 'Binary (0=No, 1=Yes)', '')
}

for col in df.columns:
    variable_names.append(col)
    dtype = df[col].dtype
    data_types.append(str(dtype))

    # Get definition and measurement from the predefined descriptions
    definition, measurement, _ = column_descriptions.get(col, ('No description available.', 'N/A', ''))
    definitions.append(definition)
    measurements.append(measurement)

    # Get other information based on data type
    if pd.api.types.is_numeric_dtype(df[col]):
        min_val = df[col].min()
        max_val = df[col].max()
        other_info.append(f'Min: {min_val:.2f}, Max: {max_val:.2f}')
    elif pd.api.types.is_object_dtype(df[col]):
        unique_vals = df[col].nunique()
        top_values = df[col].value_counts().nlargest(3).index.tolist()
        other_info.append(f'Unique values: {unique_vals}, Top 3: {top_values}')
    else:
        other_info.append('N/A')

# Create a DataFrame for the variable information
variable_df = pd.DataFrame({
    'Variable Name': variable_names,
    'Data Type': data_types,
    'Definition': definitions,
    'Measurement/Scale': measurements,
    'Summary Statistics/Unique Values': other_info
})

# Convert the DataFrame to an HTML table and display it
html_table = variable_df.to_html(index=False)

# Display the HTML table
display(HTML(html_table))

"""#### **Data Structure**"""

df.info()

"""### **Descriptive Statistics**"""

df.describe()

import numpy as np

# Identify continuous variables (numeric columns)
continuous_vars = df.select_dtypes(include=np.number).columns
# Remove 'athlete_id' from the continuous variables
continuous_vars = continuous_vars.drop('athlete_id', errors='ignore')

# Calculate descriptive statistics
stats_dict = {}
for col in continuous_vars:
    stats_dict[col] = {
        'Mean': df[col].mean(),
        'Median': df[col].median(),
        'Variance': df[col].var(),
        'Standard Deviation': df[col].std(),
        'Skewness': df[col].skew(),
        'Kurtosis': df[col].kurt(),
        'Standard Error': df[col].std() / np.sqrt(len(df[col]))
    }

#### Display the Summary Statistics
stats_dict

# Create a DataFrame from the dictionary of statistics and transpose it
descriptive_stats_df = pd.DataFrame(stats_dict)

# Display the results
descriptive_stats_df

# Create a DataFrame from the dictionary of statistics and transpose it
descriptive_stats_df = pd.DataFrame(stats_dict).T

# Display the results
descriptive_stats_df

"""### **Data Visualizaation**"""

# Calculate counts and percentages for 'injury_7d'
injury_counts = df['injury_7d'].value_counts()
injury_proportion = df['injury_7d'].value_counts(normalize = True)
injury_proportion

# Calculate counts and percentages for 'injury_7d
injury_count = df['injury_7d'].value_counts()
injury_count

# Calculate counts and percentages for 'injury_7d'
injury_counts = df['injury_7d'].value_counts()
injury_percentages = df['injury_7d'].value_counts(normalize=True) * 100
injury_percentages

# Create a bar chart using seaborn
plt.figure(figsize=(8, 6))
sns.countplot(x='injury_7d', data=df, palette='viridis')

# Add title and labels
plt.title('Distribution of Players with and Without Injury in 7 Days')
plt.xlabel('Injury in 7 Days (0: No, 1: Yes)')
plt.ylabel('Number of Players')

# Annotate bars with percentages
for index, count in enumerate(injury_counts):
    percentage = injury_percentages[index]
    plt.text(index, count + 0.1, f'{percentage:.1f}%', ha='center', va='bottom')

# Show plot
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""#### **Frequency Table for Fatigue**"""

# Calculate frequency and percentages for 'fatigue_level'
fatigue_counts = df['fatigue_level'].value_counts().sort_index()
fatigue_percentages = df['fatigue_level'].value_counts(normalize=True).mul(100).sort_index()

# Create a DataFrame for the frequency table
frequency_table = pd.DataFrame({
    'Fatigue Level': fatigue_counts.index,
    'Frequency': fatigue_counts.values,
    'Percentage': fatigue_percentages.values
})

# Calculate Cumulative Frequency (CF)
frequency_table['Cumulative Frequency (CF)'] = frequency_table['Frequency'].cumsum()

# Display the frequency table
frequency_table

"""### **Bar Chart of Fatigue Levels**"""

plt.figure(figsize=(10, 6))
sns.barplot(x='Fatigue Level', y='Frequency', data=frequency_table, palette='viridis')

plt.title('Distribution of Fatigue Levels')
plt.xlabel('Fatigue Level')
plt.ylabel('Frequency')

# Annotate bars with percentages
for index, row in frequency_table.iterrows():
    plt.text(index, row['Frequency'] + 5, f"{row['Percentage']:.1f}%", color='black', ha="center")

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""## **MACHINE LEARNING MODELING**

### **Check for Variables with Near Zero Variance**

#### **Convert all the Object Variables to Appropriate Format**
"""

# Convert 'date' column to datetime
df['date'] = pd.to_datetime(df['date'])

# Convert 'session_type' and 'position' columns to categorical type
df['session_type'] = df['session_type'].astype('category')
df['position'] = df['position'].astype('category')

# Display data types after conversion
df.info()

from sklearn.feature_selection import VarianceThreshold
X = df.drop(df.columns[[0, 2, 3, 23, 26]], axis=1)

X.head()

"""#### **Check for Zero Variance**"""

# Calculate variance for each feature
variance = X.var()
variance

# Identify zero variance predictors
zero_variance_mask = variance == 0
zero_variance_mask

# Create a DataFrame showing the variance metrics
variance_metrics = pd.DataFrame({
    'Feature': X.columns,
    'Variance': variance,
    'ZeroVariance': zero_variance_mask  # True if zero variance
})

# Print the results
variance_metrics[variance_metrics['ZeroVariance'] == True]

"""#### **Check the Variables with Near Zero Variance**"""

selector = VarianceThreshold(threshold=1e-4) # threshold = 0.0004

# Fit the model to find near-zero variance predictors
selector.fit(X)

# Get the boolean mask indicating which columns have non-zero variance
non_zero_variance_mask = selector.get_support()
non_zero_variance_mask

# Create a DataFrame showing the variance metrics
nzv_metrics = pd.DataFrame({
    'Feature': X.columns,
    'Variance': X.var(),
    'NearZeroVariance': ~non_zero_variance_mask  # True if near-zero variance
})

nzv_metrics

"""#### **Check all the Available Models**"""

from sklearn.utils import all_estimators
# Get all classifiers and regressors
estimators = all_estimators()
# Extract the names of the models
model_names = [name for name, _ in estimators]
# Display the list of model names
print(model_names)

"""#### **Select the Ten Most Important Predictor of Injury**"""

y = df['injury_7d']
print("Target variable 'y' created successfully.")
print(f"Feature set X contains 'injury_7d': {'injury_7d' in X.columns}")

y.head()

X.head()

from sklearn.ensemble import RandomForestClassifier

# Initialize the RandomForestClassifier model
rf_model = RandomForestClassifier(random_state=42)

# Fit the model to the data
rf_model.fit(X, y)

print("RandomForestClassifier model initialized and trained successfully.")

"""#### **View the Attributes in the Random Forest Model**"""

dir(rf_model)

feature_importances = rf_model.feature_importances_
feature_importances

# Create a DataFrame for feature importances
importances_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': feature_importances
})
importances_df

# Sort the features by importance in descending order
importances_df = importances_df.sort_values(by='Importance', ascending=False)
importances_df.head(10)

"""#### **Recreate the X-Object with Ten Most Important Features**"""

# Get the names of the top 10 most important features
top_10_features = importances_df.head(10)['Feature'].tolist()
top_10_features

df.head()

# Recreate the X-object with only the top 10 features
X = df[top_10_features]

print(f"X-object recreated with {len(X.columns)} features: {X.columns.tolist()}")

"""#### **View the First Few  Observations for the Predictor Variables**"""

X.head()

"""#### **View the First Few Observations for the Predicted Variable**"""

y.head()

"""#### **Split the Dataset into Training and Testing  for KNN Model Development**"""

df.info()

from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")
print(f"Number of features: {X_train.shape[1]}")

"""# 📌 **Estimate the KNN Model**

## 1️⃣ What is KNN?

**K-Nearest Neighbors (KNN)** is a **supervised learning algorithm** used for:

* ✅ Classification
* ✅ Regression

It is a **non-parametric, instance-based (lazy learning)** algorithm.

👉 It makes predictions based on the **k closest data points** in the training set.

---

## 2️⃣ Key Idea

To classify a new point:

1. Choose a value for **k**
2. Compute distance between the new point and all training points
3. Select the **k nearest neighbors**
4. Use:

   * **Majority vote** (classification)
   * **Average value** (regression)

---

## 3️⃣ Distance Metrics

KNN relies on distance measurement.

### 🔹 Euclidean Distance (Most Common)

$$
d = \sqrt{\sum_{i=1}^{n} (x_i - y_i)^2}
$$

---

### 🔹 Manhattan Distance

$$
d = \sum_{i=1}^{n} |x_i - y_i|
$$

---

### 🔹 Minkowski Distance

$$
d = \left( \sum_{i=1}^{n} |x_i - y_i|^p \right)^{1/p}
$$

* ( p = 1 ) → Manhattan
* ( p = 2 ) → Euclidean

---

## 4️⃣ Choosing K

* Small **k** → High variance, low bias (overfitting)
* Large **k** → Low variance, high bias (underfitting)

📌 Common practice:

* Use odd values (to avoid ties in binary classification)
* Use cross-validation to find best k

---

## 5️⃣ Classification Rule

For binary classification:

$$
\hat{y} = \text{mode}(y_1, y_2, ..., y_k)
$$

The predicted class is the **majority class** among neighbors.

---

## 6️⃣ Regression Rule

$$
\hat{y} = \frac{1}{k} \sum_{i=1}^{k} y_i
$$

Prediction is the **average** of the k nearest values.

---

## 7️⃣ Algorithm Steps

1. Store training dataset
2. For a new sample:

   * Compute distances
   * Sort distances
   * Pick k nearest
   * Predict

---

## 8️⃣ Advantages

✅ Simple to understand
✅ No training phase (lazy learning)
✅ Works well with small datasets
✅ Handles nonlinear boundaries

---

## 9️⃣ Disadvantages

❌ Slow for large datasets
❌ Sensitive to irrelevant features
❌ Sensitive to feature scaling
❌ Memory intensive

---

## 🔟 Importance of Feature Scaling

Since KNN uses distance:

If one feature has larger scale, it dominates.

Example:

* Age (0–100)
* Income (0–1,000,000)

Income will dominate distance.

📌 Solution:

* Standardization
* Normalization

Example in sklearn:

```python
from sklearn.preprocessing import StandardScaler
```

---

## 1️⃣1️⃣ Time Complexity

Training:
$$
O(1)
$$

Prediction:
$$
O(n \cdot d)
$$

Where:

* ( n ) = number of training samples
* ( d ) = number of features

---

## 1️⃣2️⃣ Weighted KNN

Instead of equal voting:

$$
w_i = \frac{1}{d_i}
$$

Closer neighbors get higher weight.

---

## 1️⃣3️⃣ KNN vs Decision Tree

| Feature          | KNN            | Decision Tree    |
| ---------------- | -------------- | ---------------- |
| Training time    | Very low       | Moderate         |
| Prediction time  | Slow           | Fast             |
| Interpretability | Low            | High             |
| Scaling needed   | Yes            | No               |
| Overfitting risk | High (small k) | High (deep tree) |

---

## 1️⃣4️⃣ Real-World Applications

* Image recognition
* Recommendation systems
* Fraud detection
* Medical diagnosis
* Pattern recognition

---

# 📌 Summary

KNN:

* Stores data
* Uses distance to find nearest neighbors
* Classifies by majority vote
* Regresses by averaging
* Requires proper feature scaling
* Sensitive to choice of k
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_curve, auc, accuracy_score, confusion_matrix, classification_report
from sklearn.inspection import permutation_importance

### Initialize the Training of the K-Nearest Neighbors model
knn_model = KNeighborsClassifier(n_neighbors=5)

### Train the Model
knn_model.fit(X_train, y_train)

"""#### **Predict using the KNN Estimated Model**"""

dir(knn_model)

# Make predictions
y_pred = knn_model.predict(X_test)
y_pred

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")

print(conf_matrix)

acc = (176 + 14)/(176+14+44+16)
acc

print("Classification Report:")
print(class_report)

"""The KNN model achieved an overall classification accuracy of 76% on the test dataset (n = 250).

For Class 0, the model demonstrated strong performance, with a precision of 0.80, recall of 0.92, and an F1-score of 0.85, correctly identifying the majority of instances in this class (support = 192). This indicates that the model is highly effective in predicting the majority class.

However, performance for Class 1 was considerably lower. The model achieved a precision of 0.47, recall of 0.24, and an F1-score of 0.32 (support = 58). The low recall suggests that the model failed to correctly identify a substantial proportion of Class 1 instances, indicating difficulty in detecting the minority class.

The macro-average F1-score was 0.59, reflecting moderate overall performance when treating both classes equally. The weighted-average F1-score was 0.73, influenced by the strong performance on the majority class.

Overall, while the KNN model performs well in predicting Class 0, its limited sensitivity toward Class 1 suggests potential class imbalance issues and indicates a need for further model tuning or resampling techniques to improve minority class detection.

#### **Confusion Matrix Plot**
"""

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted No Injury', 'Predicted Injury'],
            yticklabels=['Actual No Injury', 'Actual Injury'])
plt.title('Confusion Matrix for KNN Model')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""The confusion matrix for the KNN model further explains the classification performance. Out of 192 actual “No Injury” cases, 176 were correctly classified as No Injury (true negatives), while 16 were incorrectly classified as Injury (false positives). This indicates strong performance in identifying non-injury cases.

However, for the 58 actual “Injury” cases, only 14 were correctly predicted as Injury (true positives), while 44 were misclassified as No Injury (false negatives). The high number of false negatives shows that the model struggles to correctly detect injury cases.

These results align with the classification report, where recall for the Injury class was low (0.24). Although the overall accuracy is 76%, the model is biased toward the majority class (No Injury). Therefore, while KNN performs well for predicting non-injury outcomes, its limited sensitivity in identifying injuries suggests the need for class balancing or parameter tuning.

#### **ROC and AUC Value**
"""

y_pred_proba = knn_model.predict_proba(X_test)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for KNN Model')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

print(f"AUC for KNN Model: {roc_auc:.4f}")

"""The ROC curve for the KNN model shows the trade-off between the true positive rate (sensitivity) and the false positive rate across different classification thresholds. The model achieved an Area Under the Curve (AUC) of 0.61, indicating modest discriminative ability. Since an AUC of 0.50 represents random guessing, a value of 0.61 suggests that the model performs only slightly better than chance in distinguishing between Injury and No Injury cases.

The curve lies only marginally above the diagonal reference line, further confirming limited predictive power. This result aligns with the earlier findings of low recall for the Injury class. Overall, while KNN demonstrates reasonable performance for the majority class, its ability to effectively separate the two classes remains weak and may require further optimization or alternative modeling approaches.

#### **Feature Importance Plot**
"""

plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importances_df.head(10), palette='viridis')
plt.title('Features Importance Plot for the KNN Model')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

"""The feature importance plot for the KNN model, derived using permutation importance, highlights the relative contribution of each predictor variable to model performance. The most influential feature is **ACWR (Acute:Chronic Workload Ratio)**, with the highest importance score, indicating that variations in workload balance play a critical role in predicting injury risk. This suggests that sudden increases in training load relative to chronic load strongly affect classification outcomes.

Following ACWR, **acute_workload**, **heart rate variability (HRV)**, **total_distance**, and **sleep_duration** show moderate importance values. These variables are closely related to athlete workload, physiological recovery, and physical output, reinforcing their relevance in injury prediction models.

Other features such as **metabolic_power**, **chronic_workload**, **decelerations**, **player_load**, and **session RPE (srpe)** demonstrate comparatively lower but still meaningful contributions. Although their individual effects are smaller, they collectively support the predictive structure of the model.

Overall, the distribution of importance scores indicates that workload-related variables dominate the predictive process. However, given the modest ROC-AUC observed earlier, these predictors may not sufficiently separate injury from non-injury cases, suggesting potential non-linear relationships or the need for alternative modeling techniques.

## **Support Vector Machines (SVM)**

### **Support Vector Machine (SVM) – Overview**

Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification and regression tasks. In this study, SVM is applied to classify players into **Injury (1)** and **No Injury (0)** categories based on workload, physiological, and performance-related features.

SVM works by identifying an optimal hyperplane that maximizes the margin between the two classes. The data points closest to this boundary are called **support vectors**, and they determine the position of the decision boundary.

---

### **Application to the Injury Dataset**

Given that the dataset contains continuous workload variables (e.g., ACWR, acute workload, HRV, sleep duration), SVM is suitable because:

* It performs well in high-dimensional feature spaces.
* It is effective when classes are not linearly separable (using kernel functions such as RBF).
* It is robust to overfitting, especially with proper regularization (C parameter).

---

### **Important Parameters**

* **Kernel** (Linear, RBF, Polynomial)
* **C (Regularization parameter)** – controls margin width
* **Gamma (for RBF kernel)** – controls influence of individual points

---

### **Expectation for This Dataset**

Since KNN showed moderate performance and class imbalance issues, SVM with an RBF kernel and class weighting may improve minority class (Injury) detection and overall discrimination.
"""

from sklearn.svm import SVC

# Initialize the Support Vector Classifier with a linear kernel and balanced class weights
svm_model = SVC(random_state=42, probability=True, class_weight = 'balanced')

# Train the SVM model on the training data
svm_model.fit(X_train, y_train)

"""#### **Alterrnative SVM Training Process**"""

from sklearn.svm import LinearSVC
svm_model1 = LinearSVC(class_weight='balanced', random_state=42)

svm_model1.fit(X_train, y_train)

"""### **Explanation of the SVM Code**

The code above initializes and trains a **Support Vector Machine (SVM)** classifier using Scikit-learn.

#### 1️⃣ Importing the Model

```python
from sklearn.svm import SVC
```

This imports the **Support Vector Classifier (SVC)** class, which is used for classification tasks.

---

#### 2️⃣ Initializing the Model

```python
svm_model = SVC(kernel='linear', probability=True, random_state=42, class_weight='balanced')
```

This creates the SVM model with the following settings:

* **kernel='linear'**
  The model will use a linear decision boundary (a straight line or hyperplane).

* **probability=True**
  Enables probability estimates (e.g., `predict_proba()`), which are required for ROC curves and AUC calculation.

* **random_state=42**
  Ensures reproducibility of results.

* **class_weight='balanced'**
  Automatically adjusts weights inversely proportional to class frequencies.
  This is important because the dataset has class imbalance (more No Injury than Injury cases).

---

#### 3️⃣ Training the Model

```python
svm_model.fit(X_train, y_train)
```

This trains the SVM using the training feature matrix (`X_train`) and corresponding labels (`y_train`).
The model learns the optimal hyperplane that separates Injury and No Injury cases.

---

### Summary

This code builds a linear SVM model that accounts for class imbalance and is trained to classify injury vs. no-injury cases.

#### **Prediction**
"""

y_pred_svm = svm_model.predict(X_test)
y_pred_svm

"""##### **Model Performance Metrics**"""

accuracy_svm = accuracy_score(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
class_report_svm = classification_report(y_test, y_pred_svm)

print(f"SVM Model Accuracy: {accuracy_svm:.4f}")
print("\nSVM Model Confusion Matrix:")
print(conf_matrix_svm)
print("\nSVM Model Classification Report:")
print(class_report_svm)

"""The Support Vector Machine (SVM) model achieved an overall accuracy of **66.8%** on the test dataset (n = 250). From the confusion matrix, 138 out of 192 actual *No Injury* cases were correctly classified (true negatives), while 54 were incorrectly predicted as injuries (false positives). For the *Injury* class, 29 out of 58 cases were correctly identified (true positives), and 29 were misclassified as no injury (false negatives).

The classification report shows strong performance for Class 0, with a precision of **0.83**, recall of **0.72**, and F1-score of **0.77**. For Class 1 (Injury), the model achieved a precision of **0.35**, recall of **0.50**, and F1-score of **0.41**. Compared to KNN, SVM improved recall for the minority Injury class but reduced overall accuracy. The macro-average F1-score of **0.59** indicates moderate balanced performance, suggesting improved sensitivity but continued challenges in accurately distinguishing injury cases.

#### **Confusion  Matrix Plot**
"""

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix_svm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted No Injury', 'Predicted Injury'],
            yticklabels=['Actual No Injury', 'Actual Injury'])
plt.title('Confusion Matrix for SVM Model')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""#### **ROC Curve and AUC**"""

y_pred_proba_svm = svm_model.predict_proba(X_test)[:, 1]
fpr_svm, tpr_svm, thresholds_svm = roc_curve(y_test, y_pred_proba_svm)
roc_auc_svm = auc(fpr_svm, tpr_svm)

"""### 1️⃣ Getting Predicted Probabilities

```python
y_pred_proba_svm = svm_model.predict_proba(X_test)[:, 1]
```

* `predict_proba(X_test)` returns the probability of each class for every observation in the test set.
* The output has two columns:

  * Column 0 → Probability of Class 0 (No Injury)
  * Column 1 → Probability of Class 1 (Injury)
* `[:, 1]` selects only the probabilities for the **positive class (Injury)**.

This step extracts the predicted probabilities of the Injury class, which are required to compute the ROC curve.

---

### 2️⃣ Computing ROC Curve Values

```python
fpr_svm, tpr_svm, thresholds_svm = roc_curve(y_test, y_pred_proba_svm)
```

This calculates:

* **FPR (False Positive Rate)**
* **TPR (True Positive Rate / Recall)**
* **Thresholds** used to classify probabilities into classes

The ROC curve shows how sensitivity and specificity change across thresholds.

---

### 3️⃣ Calculating AUC

```python
roc_auc_svm = auc(fpr_svm, tpr_svm)
```

This computes the **Area Under the Curve (AUC)**, which summarizes the model’s ability to distinguish between Injury and No Injury. Higher AUC indicates better discrimination performance.

"""

plt.figure(figsize=(8, 6))
plt.plot(fpr_svm, tpr_svm, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc_svm:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for SVM Model')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

print(f"AUC for SVM Model: {roc_auc_svm:.4f}")

"""# 🌳 **Decision Tree**

## 1️⃣ What is a Decision Tree?

A **Decision Tree** is a **supervised machine learning algorithm** used for:

* ✅ Classification (e.g., Injury vs No Injury)
* ✅ Regression (predicting continuous values)

It splits data into branches based on feature values to make predictions.

It looks like a flowchart:

* Root node → Decision nodes → Leaf nodes

---

## 2️⃣ Key Terminology

### 🔹 Root Node

* The first split of the dataset.
* Represents the most important feature.

### 🔹 Decision Node

* A node where the data is split based on a condition.
* Example: `Age ≤ 35`

### 🔹 Leaf Node (Terminal Node)

* Final output (prediction).
* Example: "Injury"

### 🔹 Branch

* Outcome of a split.

### 🔹 Depth

* Number of levels in the tree.
* Larger depth = more complex tree.

---

## 3️⃣ How Decision Trees Work

Decision trees split the dataset using a criterion that measures impurity.

At each node:

1. Try different splits
2. Calculate impurity
3. Choose the split that reduces impurity the most

This process continues until:

* Maximum depth is reached
* All samples belong to one class
* Minimum samples per split condition is met

---

## 4️⃣ Splitting Criteria (Impurity Measures)

### 📌 For Classification

### 🔹 Gini Index

Most common in sklearn.

Formula:
$$
Gini = 1 - \sum p_i^2
$$

* 0 = pure node
* Higher value = more mixed classes

---

### 🔹 Entropy (Information Gain)

Based on information theory.

$$
Entropy = -\sum p_i \log_2(p_i)
$$

Information Gain:
$$
IG = Entropy(parent) - Weighted\ Entropy(children)
$$

Higher information gain = better split.

---

### 📌 For Regression

### 🔹 Mean Squared Error (MSE)

Measures variance in continuous values.

---

## 5️⃣ Pruning (Controlling Overfitting)

Decision trees easily overfit.

### 🔹 Overfitting

* Model learns noise
* Performs well on training data
* Poor performance on test data

### 🔹 Methods to Prevent Overfitting

| Parameter           | Purpose                         |
| ------------------- | ------------------------------- |
| `max_depth`         | Maximum levels of tree          |
| `min_samples_split` | Minimum samples needed to split |
| `min_samples_leaf`  | Minimum samples in leaf         |
| `max_leaf_nodes`    | Limit number of leaf nodes      |

Example:

```python
DecisionTreeClassifier(max_depth=4)
```

This creates a **pruned tree**.

---

## 6️⃣ Advantages of Decision Trees

✅ Easy to understand
✅ Easy to visualize
✅ No need for feature scaling
✅ Works with numerical and categorical data
✅ Handles nonlinear relationships

---

## 7️⃣ Disadvantages

❌ Prone to overfitting
❌ Unstable (small data changes → different tree)
❌ Can be biased toward dominant classes

---

## 8️⃣ Feature Importance

Decision trees can rank features by importance.

* Features that reduce impurity more are more important.
* In sklearn:

```python
model.feature_importances_
```

---

## 9️⃣ Decision Tree Example

Suppose predicting Injury:

Root node:

```
Speed ≤ 60?
```

If YES → Low Risk
If NO → Check Experience

This continues until prediction is made.

---

## 🔟 Decision Tree vs Other Models

| Model               | Interpretation | Overfitting Risk |
| ------------------- | -------------- | ---------------- |
| Logistic Regression | Medium         | Low              |
| Decision Tree       | Very High      | High             |
| Random Forest       | Low            | Low              |
| Gradient Boosting   | Low            | Medium           |

---

## 1️⃣1️⃣ Real-World Applications

* Medical diagnosis
* Credit risk analysis
* Fraud detection
* Customer churn prediction
* Accident prediction

---

# 📌 Summary

A Decision Tree:

* Splits data using impurity measures
* Creates a tree-like structure
* Is easy to interpret
* Needs pruning to avoid overfitting
* Is the foundation for Random Forest & Boosting models

"""

from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier with balanced class weights
dt_model = DecisionTreeClassifier(random_state=42, class_weight='balanced')

# Train the Decision Tree model on the training data
dt_model.fit(X_train, y_train)

"""#### **Prediction**"""

y_pred_dt = dt_model.predict(X_test)
y_pred_dt

"""#### **Model's Performance Metrics**"""

accuracy_dt = accuracy_score(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)
class_report_dt = classification_report(y_test, y_pred_dt)

print(f"Decision Tree Model Accuracy: {accuracy_dt:.4f}")
print("\nDecision Tree Model Confusion Matrix:")
print(conf_matrix_dt)
print("\nDecision Tree Model Classification Report:")
print(class_report_dt)

"""#### **Confusion Matrix Plot**"""

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix_dt, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted No Injury', 'Predicted Injury'],
            yticklabels=['Actual No Injury', 'Actual Injury'])
plt.title('Confusion Matrix for Decision Tree Model')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""#### **ROC and AUC Curve**"""

y_pred_proba_dt = dt_model.predict_proba(X_test)[:, 1]
fpr_dt, tpr_dt, thresholds_dt = roc_curve(y_test, y_pred_proba_dt)
roc_auc_dt = auc(fpr_dt, tpr_dt)

plt.figure(figsize=(8, 6))
plt.plot(fpr_dt, tpr_dt, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc_dt:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Decision Tree Model')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

print(f"AUC for Decision Tree Model: {roc_auc_dt:.4f}")

"""#### **Plot the Decision Tree**"""

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 15))
plot_tree(dt_model, filled=True, feature_names=X.columns.tolist(), class_names=['No Injury', 'Injury'], rounded=True)
plt.title('Decision Tree Visualization')
plt.show()

"""#### **Retrain the Decision Tree with Pruned Branches**"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# Re-initialize the Decision Tree Classifier with a constrained max_depth and balanced class weights
dt_pruned_model = DecisionTreeClassifier(max_depth=3, random_state=42, class_weight='balanced')

# Train the pruned Decision Tree model on the training data
dt_pruned_model.fit(X_train, y_train)

print("Pruned Decision Tree model trained successfully.")

# Plot the pruned Decision Tree
plt.figure(figsize=(20, 12))
plot_tree(dt_pruned_model, filled=True, feature_names=X.columns.tolist(), class_names=['No Injury', 'Injury'], rounded=True)
plt.title('Pruned Decision Tree Visualization (max_depth=4)')
plt.show()

"""This code **visualizes a pruned Decision Tree model** using `matplotlib` and `sklearn`.

### 1️⃣ Create a Large Figure

```python
plt.figure(figsize=(20, 12))
```

* Uses **`matplotlib`** to create a plotting canvas.
* `figsize=(20, 12)` makes the figure **20 inches wide and 12 inches tall**.
* A large size is used so the decision tree is easier to read.

---

### 2️⃣ Plot the Decision Tree

```python
plot_tree(
    dt_pruned_model,
    filled=True,
    feature_names=X.columns.tolist(),
    class_names=['No Injury', 'Injury'],
    rounded=True
)
```

This uses `plot_tree()` from **scikit-learn** to visualize the trained model.

#### 🔹 `dt_pruned_model`

* This is your **trained decision tree classifier**.
* It is “pruned” (limited in complexity).
* From the title, it likely has `max_depth=4`, meaning:

  * The tree can only grow 4 levels deep.
  * This reduces overfitting.

#### 🔹 `filled=True`

* Colors each node based on the predicted class.
* Darker color = higher purity (more confident prediction).

#### 🔹 `feature_names=X.columns.tolist()`

* Displays the actual **feature names** at each split.
* `X.columns.tolist()` converts your dataset column names into a list.

#### 🔹 `class_names=['No Injury', 'Injury']`

* Labels the output classes.
* Instead of showing 0 and 1, it shows:

  * `No Injury`
  * `Injury`

#### 🔹 `rounded=True`

* Makes node boxes have rounded corners for better appearance.

---

### 3️⃣ Add a Title

```python
plt.title('Pruned Decision Tree Visualization (max_depth=4)')
```

* Adds a descriptive title to the plot.
* Indicates that the tree was pruned using `max_depth=4`.

---

### 4️⃣ Display the Plot

```python
plt.show()
```

* Renders and displays the decision tree visualization.

---

# ✅ What the Entire Code Does

It creates a **large, readable visualization of a pruned decision tree classifier**, showing:

* The feature used at each split
* The threshold values
* The number of samples at each node
* Class distribution at each node
* Final predicted class (Injury / No Injury)
* Color intensity showing prediction confidence

---

# 🎯 Why This Is Useful

This visualization helps you:

* Understand how your model makes decisions
* Interpret which features are most important
* Check if pruning (max_depth=4) simplified the tree
* Present results in reports or presentations

This plot shows a **pruned decision tree** (max_depth = 4) for predicting sports injury risk, built from 1,000 samples (500 injured, 500 not injured). The root node splits on **acwr ≤ 1.5** (acute:chronic workload ratio), with balanced impurity (Gini = 0.5).

The left branch (acwr ≤ 1.5, 741 samples) leads to further splits on **acwr ≤ 0.803**, then **metabolic_power ≤ 9.543** and **srpe ≤ 79.0**. Notably, the leaf with *metabolic_power ≤ 9.543* has high injury prevalence: 124 samples, 49 injuries vs. 111 non-injuries (≈30% injury rate), and is labeled “class = Injury” — indicating the model predicts injury here. In contrast, the sibling leaf (*metabolic_power > 9.543*) has only 38 samples with 20 injuries (≈53% injury rate) but is labeled “class = No Injury”, suggesting the majority class rule misclassifies this high-risk node — a potential limitation.

The right branch (acwr > 1.5, 259 samples) splits on **hrv ≤ 69.537** (heart rate variability), then on **decelerations ≤ 33.5** and **player_load ≤ 383.013**. Most terminal nodes in this branch predict *Injury*, especially where decelerations are low (e.g., 220 samples, 78 injuries → ~35% injury rate).

Gini values decrease toward leaves (e.g., 0.267–0.469), indicating improved purity. However, several leaves still show mixed classes and relatively high Gini (>0.3), reflecting inherent uncertainty. The tree prioritizes workload (acwr) and recovery markers (hrv) as top predictors, aligning with sports science literature.

#### **ROC and AUC for the Pruned Decisin Tree**
"""

y_pred_proba_dt_pruned = dt_pruned_model.predict_proba(X_test)[:, 1]
fpr_dt_pruned, tpr_dt_pruned, thresholds_dt_pruned = roc_curve(y_test, y_pred_proba_dt_pruned)
roc_auc_dt_pruned = auc(fpr_dt_pruned, tpr_dt_pruned)

plt.figure(figsize=(8, 6))
plt.plot(fpr_dt_pruned, tpr_dt_pruned, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc_dt_pruned:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve for Pruned Decision Tree Model')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

print(f"AUC for Pruned Decision Tree Model: {roc_auc_dt_pruned:.4f}")

"""### **Comparative Analysis of the Three Models**"""

import pandas as pd
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

# --- Extract Metrics for KNN Model ---
# Accuracy is already calculated as `accuracy`
# AUC is already calculated as `roc_auc`

# Parse classification report for class 1 (Injury)
report_knn = classification_report(y_test, y_pred, output_dict=True)
precision_knn = report_knn['1']['precision']
recall_knn = report_knn['1']['recall']
f1_knn = report_knn['1']['f1-score']

# --- Extract Metrics for SVM Model ---
# Accuracy is already calculated as `accuracy_svm`
# AUC is already calculated as `roc_auc_svm`

# Parse classification report for class 1 (Injury)
report_svm = classification_report(y_test, y_pred_svm, output_dict=True)
precision_svm = report_svm['1']['precision']
recall_svm = report_svm['1']['recall']
f1_svm = report_svm['1']['f1-score']

# --- Extract Metrics for Pruned Decision Tree Model ---
# Make predictions for the pruned DT model
y_pred_dt = dt_model.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)

# Calculate AUC for pruned DT
y_pred_proba_dt = dt_model.predict_proba(X_test)[:, 1]
roc_auc_dt = roc_auc_score(y_test, y_pred_proba_dt)

# Parse classification report for class 1 (Injury)
report_dt = classification_report(y_test, y_pred_dt, output_dict=True)
precision_dt = report_dt['1']['precision']
recall_dt = report_dt['1']['recall']
f1_dt = report_dt['1']['f1-score']

# Create a DataFrame for comparison
comparison_df = pd.DataFrame({
    'Model': ['KNN', 'SVM', 'Decision Tree'],
    'Accuracy': [accuracy, accuracy_svm, accuracy_dt],
    'Precision (Class 1)': [precision_knn, precision_svm, precision_dt],
    'Recall (Class 1)': [recall_knn, recall_svm, recall_dt],
    'F1-Score (Class 1)': [f1_knn, f1_svm, f1_dt],
    'AUC': [roc_auc, roc_auc_svm, roc_auc_dt]
})

# Set Model as index for better readability
comparison_df = comparison_df.set_index('Model')

print("\n--- Model Performance Comparison ---")
comparison_df

"""Based on the evaluation metrics provided, the **best model depends on the objective**, but overall, the **SVM (Support Vector Machine)** appears to be the strongest choice.

First, although **KNN** has the highest **accuracy (0.760)**, accuracy alone can be misleading—especially if the dataset is imbalanced. In such cases, a model may predict the majority class well while performing poorly on the minority class (Class 1). This is evident in KNN’s **low recall (0.241)**, meaning it correctly identifies only about 24% of actual Class 1 cases. That is quite weak if detecting Class 1 (e.g., injury cases) is important.

The **Decision Tree** performs moderately, with accuracy of **0.724**, but it has the lowest AUC (**0.562**) among the three models. Its precision and recall are also relatively low, resulting in a weak F1-score (**0.303**). This suggests limited ability to distinguish between classes.

The **SVM**, while having lower accuracy (**0.668**), performs best in more meaningful metrics for Class 1 detection. It has the highest **recall (0.500)**, meaning it correctly identifies 50% of Class 1 cases—significantly better than KNN and the Decision Tree. It also has the highest **F1-score (0.411)**, which balances precision and recall. Additionally, SVM achieves the highest **AUC (0.630)**, indicating better overall discrimination between classes.

Therefore, if identifying Class 1 correctly is important, **SVM is the best model overall** because it provides better balance, higher recall, and superior AUC performance.

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# import sqlite3
# import json
# import os
# import time
# from datetime import datetime
# 
# # ============================================================================
# # 💾 DATABASE SETUP
# # ============================================================================
# DB_FILE = 'sports_performance.db'
# 
# def init_database():
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
# 
#     cursor.execute('''
#         CREATE TABLE IF NOT EXISTS athletes (
#             id INTEGER PRIMARY KEY AUTOINCREMENT,
#             name TEXT NOT NULL,
#             sport TEXT,
#             age INTEGER,
#             weight REAL,
#             registered_date TEXT
#         )
#     ''')
# 
#     cursor.execute('''
#         CREATE TABLE IF NOT EXISTS kpi_records (
#             id INTEGER PRIMARY KEY AUTOINCREMENT,
#             athlete_name TEXT,
#             heart_rate INTEGER,
#             sleep_hours REAL,
#             fatigue_score INTEGER,
#             training_load INTEGER,
#             stamina INTEGER,
#             speed REAL,
#             risk_score REAL,
#             prediction TEXT,
#             model_used TEXT,
#             timestamp TEXT
#         )
#     ''')
# 
#     conn.commit()
#     conn.close()
# 
# init_database()
# 
# # ============================================================================
# # 🔐 AUTHENTICATION SETUP
# # ============================================================================
# AUTH_FILE = 'auth_config.json'
# 
# def init_auth():
#     if not os.path.exists(AUTH_FILE):
#         credentials = {
#             'admin': 'admin@2024',
#             'daniel': 'research@123',
#             'researcher': 'sports@ai2024',
#             'user': 'demo123'
#         }
#         with open(AUTH_FILE, 'w') as f:
#             json.dump(credentials, f, indent=2)
# 
# init_auth()
# 
# # ============================================================================
# # 🔐 PAGE CONFIG
# # ============================================================================
# st.set_page_config(
#     page_title="AI Sports Performance Monitoring",
#     layout="wide",
#     page_icon="🏅"
# )
# 
# if 'logged_in' not in st.session_state:
#     st.session_state['logged_in'] = False
# if 'username' not in st.session_state:
#     st.session_state['username'] = None
# 
# # ============================================================================
# # 🗄️ DATABASE FUNCTIONS
# # ============================================================================
# def get_athletes_from_db():
#     try:
#         conn = sqlite3.connect(DB_FILE)
#         df = pd.read_sql_query("SELECT * FROM athletes ORDER BY name", conn)
#         conn.close()
#         return df
#     except:
#         return pd.DataFrame()
# 
# def add_athlete_to_db(name, sport, age, weight):
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute('''
#         INSERT INTO athletes (name, sport, age, weight, registered_date)
#         VALUES (?, ?, ?, ?, ?)
#     ''', (name, sport, age, weight, datetime.now().strftime("%Y-%m-%d")))
#     conn.commit()
#     conn.close()
# 
# def delete_athlete_from_db(athlete_id):
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute("DELETE FROM athletes WHERE id=?", (athlete_id,))
#     conn.commit()
#     conn.close()
# 
# def get_kpi_records():
#     try:
#         conn = sqlite3.connect(DB_FILE)
#         df = pd.read_sql_query("SELECT * FROM kpi_records ORDER BY timestamp DESC", conn)
#         conn.close()
#         return df
#     except:
#         return pd.DataFrame()
# 
# def save_kpi_record(athlete_name, hr, sleep, fatigue, t_load, stamina, speed, risk_score, prediction, model):
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute('''
#         INSERT INTO kpi_records
#         (athlete_name, heart_rate, sleep_hours, fatigue_score, training_load,
#          stamina, speed, risk_score, prediction, model_used, timestamp)
#         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     ''', (athlete_name, hr, sleep, fatigue, t_load, stamina, speed,
#           risk_score, prediction, model, datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
#     conn.commit()
#     conn.close()
# 
# def get_athlete_count():
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute("SELECT COUNT(*) FROM athletes")
#     count = cursor.fetchone()[0]
#     conn.close()
#     return count
# 
# def get_high_risk_count():
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute("""
#         SELECT COUNT(*) FROM kpi_records
#         WHERE prediction LIKE '%HIGH%'
#         AND timestamp >= datetime('now', '-7 days')
#     """)
#     count = cursor.fetchone()[0]
#     conn.close()
#     return count
# 
# def get_avg_performance():
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute("""
#         SELECT AVG(stamina) FROM kpi_records
#         WHERE timestamp >= datetime('now', '-7 days')
#     """)
#     avg = cursor.fetchone()[0]
#     conn.close()
#     return round(avg, 1) if avg else 0.0
# 
# def get_recent_alerts():
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute('''
#         SELECT athlete_name, timestamp, risk_score, prediction
#         FROM kpi_records
#         WHERE prediction LIKE '%HIGH%' OR prediction LIKE '%MODERATE%'
#         ORDER BY timestamp DESC
#         LIMIT 5
#     ''')
#     alerts = cursor.fetchall()
#     conn.close()
#     return alerts
# 
# def get_total_kpi_records():
#     conn = sqlite3.connect(DB_FILE)
#     cursor = conn.cursor()
#     cursor.execute("SELECT COUNT(*) FROM kpi_records")
#     count = cursor.fetchone()[0]
#     conn.close()
#     return count
# 
# # ============================================================================
# # 🎨 CSS STYLING - FIXED ALL TEXT VISIBILITY!
# # ============================================================================
# def load_custom_css():
#     st.markdown("""
#     <style>
#     @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
# 
#     * {
#         font-family: 'Inter', sans-serif;
#     }
# 
#     /* ===== MAIN BACKGROUND ===== */
#     .stApp {
#         background: linear-gradient(135deg, #1a0033 0%, #2d0066 25%, #3d0066 50%, #2d004d 75%, #1a0033 100%);
#         background-attachment: fixed;
#         min-height: 100vh;
#     }
# 
#     /* ===== MAIN CONTAINER ===== */
#     .main-container {
#         background: rgba(255, 255, 255, 0.03);
#         backdrop-filter: blur(20px);
#         -webkit-backdrop-filter: blur(20px);
#         border-radius: 30px;
#         padding: 35px;
#         margin: 20px;
#         border: 1px solid rgba(255, 255, 255, 0.08);
#         box-shadow: 0 25px 50px rgba(0, 0, 0, 0.3);
#     }
# 
#     /* ===== LOGIN CONTAINER ===== */
#     .login-container {
#         background: rgba(255, 255, 255, 0.05);
#         backdrop-filter: blur(30px);
#         padding: 60px 50px;
#         border-radius: 30px;
#         max-width: 500px;
#         margin: 80px auto;
#         text-align: center;
#         border: 1px solid rgba(255, 255, 255, 0.1);
#     }
# 
#     .login-title {
#         background: linear-gradient(135deg, #00f2fe 0%, #8a2be2 50%, #ff1493 100%);
#         -webkit-background-clip: text;
#         -webkit-text-fill-color: transparent;
#         font-weight: 800;
#         font-size: 32px;
#         margin: 0 0 10px 0;
#     }
# 
#     /* ===== METRIC CARDS ===== */
#     .metric-card {
#         background: linear-gradient(135deg, rgba(138, 43, 226, 0.4), rgba(255, 20, 147, 0.4));
#         backdrop-filter: blur(20px);
#         color: white;
#         padding: 25px 20px;
#         border-radius: 24px;
#         text-align: center;
#         box-shadow: 0 15px 40px rgba(138, 43, 226, 0.3);
#         border: 1px solid rgba(255, 255, 255, 0.2);
#         transition: all 0.3s;
#     }
# 
#     .metric-card:hover {
#         transform: translateY(-8px);
#         box-shadow: 0 25px 60px rgba(138, 43, 226, 0.5);
#     }
# 
#     .metric-card h3 {
#         margin: 10px 0 5px 0;
#         font-size: 34px;
#         font-weight: 800;
#         color: #ffffff !important;
#         text-shadow: 0 2px 4px rgba(0,0,0,0.3);
#     }
# 
#     .metric-card p {
#         margin: 0;
#         font-size: 13px;
#         color: #ffffff !important;
#         font-weight: 600;
#     }
# 
#     .metric-card .icon {
#         font-size: 30px;
#         margin-bottom: 8px;
#         display: block;
#     }
# 
#     /* ===== HEADERS - BRIGHT WHITE ===== */
#     h1 {
#         background: linear-gradient(135deg, #00f2fe, #8a2be2, #ff1493);
#         -webkit-background-clip: text;
#         -webkit-text-fill-color: transparent;
#         font-weight: 800;
#     }
# 
#     h2, h3, h4, h5, h6 {
#         color: #ffffff !important;
#         font-weight: 700;
#         text-shadow: 0 2px 4px rgba(0,0,0,0.3);
#     }
# 
#     /* ===== ALL TEXT - WHITE & VISIBLE ===== */
#     p, span, label, div, li, a {
#         color: #ffffff !important;
#         font-weight: 500;
#     }
# 
#     /* ===== FORM INPUTS - BLACK TEXT ON WHITE ===== */
#     .stTextInput > div > div > input,
#     .stNumberInput > div > div > input {
#         border-radius: 14px;
#         border: 2px solid rgba(255, 255, 255, 0.4);
#         background: #ffffff !important;
#         color: #000000 !important;
#         font-weight: 600;
#         font-size: 15px;
#     }
# 
#     .stTextInput > div > div > input:focus,
#     .stNumberInput > div > div > input:focus {
#         border-color: #8a2be2;
#         box-shadow: 0 0 0 4px rgba(138, 43, 226, 0.4);
#         background: #ffffff !important;
#         color: #000000 !important;
#     }
# 
#     /* ===== INPUT LABELS - BRIGHT WHITE ===== */
#     .stTextInput label,
#     .stNumberInput label,
#     .stSelectbox label,
#     .stSlider label {
#         color: #ffffff !important;
#         font-weight: 600;
#         font-size: 14px;
#     }
# 
#     /* ===== SELECT BOX - BLACK TEXT ON WHITE ===== */
#     .stSelectbox > div > div > div,
#     .stSelectbox input {
#         background: #ffffff !important;
#         color: #000000 !important;
#         font-weight: 600;
#     }
# 
#     /* ===== SLIDER - WHITE TEXT ===== */
#     .stSlider > div > div {
#         color: #ffffff !important;
#         font-weight: 600;
#     }
# 
#     /* ===== BUTTONS ===== */
#     .stButton > button {
#         background: linear-gradient(135deg, #8a2be2, #ff1493);
#         color: #ffffff !important;
#         border: none;
#         border-radius: 15px;
#         padding: 14px 32px;
#         font-weight: 700;
#         font-size: 14px;
#         width: 100%;
#         box-shadow: 0 10px 30px rgba(138, 43, 226, 0.4);
#     }
# 
#     .stButton > button:hover {
#         transform: translateY(-3px);
#         box-shadow: 0 15px 40px rgba(138, 43, 226, 0.6);
#         color: #ffffff !important;
#     }
# 
#     /* ===== TABS ===== */
#     .stTabs [data-baseweb="tab-list"] {
#         gap: 15px;
#         background: rgba(255, 255, 255, 0.05);
#         border-radius: 20px;
#         padding: 12px;
#         margin-bottom: 30px;
#     }
# 
#     .stTabs [data-baseweb="tab"] {
#         height: 55px;
#         background: linear-gradient(135deg, rgba(138, 43, 226, 0.3), rgba(255, 20, 147, 0.3));
#         border-radius: 15px;
#         padding: 14px 28px;
#         font-weight: 600;
#         color: #ffffff !important;
#     }
# 
#     .stTabs [aria-selected="true"] {
#         background: linear-gradient(135deg, #8a2be2, #ff1493, #00f2fe);
#         color: #ffffff !important;
#     }
# 
#     /* ===== STATUS CARDS - DARKER BACKGROUND ===== */
#     .status-card {
#         padding: 14px 18px;
#         border-radius: 16px;
#         margin: 8px 0;
#         backdrop-filter: blur(15px);
#         border: 1px solid rgba(255, 255, 255, 0.2);
#     }
# 
#     .status-success {
#         background: rgba(16, 185, 129, 0.4) !important;
#         color: #ffffff !important;
#     }
# 
#     .status-warning {
#         background: rgba(245, 158, 11, 0.4) !important;
#         color: #ffffff !important;
#     }
# 
#     .status-error {
#         background: rgba(239, 68, 68, 0.4) !important;
#         color: #ffffff !important;
#     }
# 
#     /* ===== METRICS - WHITE TEXT ===== */
#     [data-testid="stMetric"] {
#         background: rgba(255, 255, 255, 0.1);
#         padding: 15px;
#         border-radius: 12px;
#         border: 1px solid rgba(255, 255, 255, 0.15);
#     }
# 
#     [data-testid="stMetric"] label {
#         color: #ffffff !important;
#         font-weight: 600;
#     }
# 
#     [data-testid="stMetricValue"] {
#         color: #ffffff !important;
#         font-weight: 700;
#         font-size: 24px;
#     }
# 
#     [data-testid="stMetricDelta"] {
#         color: #00f2fe !important;
#         font-weight: 600;
#     }
# 
#     /* ===== FOOTER ===== */
#     .footer {
#         text-align: center;
#         padding: 25px;
#         color: rgba(255, 255, 255, 0.7) !important;
#         margin-top: 15px;
#         border-top: 1px solid rgba(255, 255, 255, 0.1);
#     }
# 
#     /* ===== DATAFRAME - WHITE BACKGROUND ===== */
#     .dataframe {
#         border-radius: 18px;
#         overflow: hidden;
#         box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
#         background: #ffffff !important;
#     }
# 
#     .dataframe td, .dataframe th {
#         color: #000000 !important;
#         font-weight: 500;
#     }
# 
#     /* ===== ALERTS - VISIBLE TEXT ===== */
#     .stAlert {
#         border-radius: 16px;
#         border: none;
#         box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
#         margin: 12px 0;
#     }
# 
#     .stAlert * {
#         color: #000000 !important;
#         font-weight: 600;
#     }
# 
#     /* ===== EXPANDERS ===== */
#     .streamlit-expanderHeader {
#         background: rgba(255, 255, 255, 0.1);
#         border-radius: 16px;
#         border: 1px solid rgba(255, 255, 255, 0.15);
#         color: #ffffff !important;
#     }
# 
#     .streamlit-expanderHeader * {
#         color: #ffffff !important;
#     }
# 
#     /* ===== SIDEBAR ===== */
#     [data-testid="stSidebar"] {
#         background: rgba(26, 0, 51, 0.8);
#     }
# 
#     [data-testid="stSidebar"] * {
#         color: #ffffff !important;
#     }
#     </style>
#     """, unsafe_allow_html=True)
# 
# # ============================================================================
# # 🔐 AUTHENTICATION
# # ============================================================================
# def authenticate_user(username, password):
#     try:
#         with open(AUTH_FILE, 'r') as f:
#             credentials = json.load(f)
#         return credentials.get(username) == password
#     except:
#         return False
# 
# def login_page():
#     load_custom_css()
#     col1, col2, col3 = st.columns([1, 2, 1])
#     with col2:
#         st.markdown('<div class="login-container">', unsafe_allow_html=True)
#         st.markdown('<p class="login-title">🏅 AI Sports Performance</p>', unsafe_allow_html=True)
#         st.markdown('<p style="color: rgba(255,255,255,0.8);">Advanced Sports Analytics Dashboard</p>', unsafe_allow_html=True)
# 
#         username = st.text_input("👤 Username", key="login_user", label_visibility="collapsed")
#         password = st.text_input("🔑 Password", type="password", key="login_pass", label_visibility="collapsed")
# 
#         if st.button("🚀 Access Dashboard", key="login_btn"):
#             if authenticate_user(username, password):
#                 st.session_state['logged_in'] = True
#                 st.session_state['username'] = username
#                 st.success("✨ Welcome back!")
#                 time.sleep(1)
#                 st.rerun()
#             else:
#                 st.error("❌ Invalid credentials")
# 
#         st.markdown("</div>", unsafe_allow_html=True)
# 
# # ============================================================================
# # 📊 MAIN DASHBOARD
# # ============================================================================
# def dashboard():
#     load_custom_css()
# 
#     col1, col2, col3 = st.columns([3, 1, 1])
#     with col1:
#         st.title("🏅 AI-Driven Sports Performance Monitoring")
#         st.markdown(f"*Advanced Sports Analytics Lab* • 👤 **{st.session_state['username']}**")
#     with col3:
#         if st.button("🚪 Logout", key="logout_btn"):
#             st.session_state['logged_in'] = False
#             st.session_state['username'] = None
#             st.rerun()
# 
#     st.markdown('<div class="main-container">', unsafe_allow_html=True)
# 
#     tab1, tab2, tab3, tab4, tab5 = st.tabs([
#         "📈 Dashboard", "👥 Athletes", "⚙️ KPI & Predict", "📊 Analytics", "💾 Database"
#     ])
# 
#     # ========================================================================
#     # TAB 1: DASHBOARD
#     # ========================================================================
#     with tab1:
#         st.header("🎯 Performance Overview")
# 
#         athlete_count = get_athlete_count()
#         high_risk_count = get_high_risk_count()
#         avg_performance = get_avg_performance()
#         total_records = get_total_kpi_records()
#         recent_alerts = get_recent_alerts()
# 
#         col1, col2, col3, col4 = st.columns(4)
#         with col1:
#             st.markdown(f'<div class="metric-card"><span class="icon">👥</span><h3>{athlete_count}</h3><p>Active Athletes</p></div>', unsafe_allow_html=True)
#         with col2:
#             st.markdown(f'<div class="metric-card"><span class="icon">⚠️</span><h3>{high_risk_count}</h3><p>High Risk (7 days)</p></div>', unsafe_allow_html=True)
#         with col3:
#             st.markdown(f'<div class="metric-card"><span class="icon">✅</span><h3>{avg_performance}%</h3><p>Avg Performance</p></div>', unsafe_allow_html=True)
#         with col4:
#             st.markdown(f'<div class="metric-card"><span class="icon">📊</span><h3>{total_records}</h3><p>Total Records</p></div>', unsafe_allow_html=True)
# 
#         st.markdown("---")
# 
#         col1, col2 = st.columns([2, 1])
# 
#         with col1:
#             st.subheader("📈 Weekly Performance Trends")
#             kpi_df = get_kpi_records()
#             if not kpi_df.empty:
#                 kpi_df['date'] = pd.to_datetime(kpi_df['timestamp']).dt.date
#                 daily_avg = kpi_df.groupby('date')['stamina'].mean().tail(7).reset_index()
#                 daily_avg.columns = ['Day', 'Performance']
#                 daily_avg['Day'] = daily_avg['Day'].apply(lambda x: x.strftime('%a'))
# 
#                 fig = go.Figure()
#                 fig.add_trace(go.Scatter(x=daily_avg['Day'], y=daily_avg['Performance'],
#                                        mode='lines+markers', name='Performance',
#                                        line=dict(color='#00f2fe', width=4),
#                                        marker=dict(size=10, color='#00f2fe')))
#                 fig.update_layout(template='plotly_dark', height=380,
#                                 title='Daily Performance Trend',
#                                 plot_bgcolor='rgba(0,0,0,0.5)',
#                                 paper_bgcolor='rgba(0,0,0,0.5)',
#                                 font=dict(color='#ffffff', size=12),
#                                 legend=dict(bgcolor='rgba(0,0,0,0.5)', font=dict(color='#ffffff')))
#                 st.plotly_chart(fig, use_container_width=True)
#             else:
#                 st.info("📊 No performance data yet. Add KPI records in Tab 3!")
# 
#         with col2:
#             st.subheader("🔔 Recent Alerts")
#             if recent_alerts:
#                 for alert in recent_alerts:
#                     athlete, timestamp, risk, prediction = alert
#                     risk_level = "🚨 HIGH" if "HIGH" in prediction else "⚠️ MODERATE"
#                     status_class = "error" if "HIGH" in prediction else "warning"
#                     st.markdown(f"""
#                     <div class="status-card status-{status_class}">
#                         <strong>{risk_level}</strong> - {athlete}<br>
#                         <small>{timestamp}</small>
#                     </div>
#                     """, unsafe_allow_html=True)
#             else:
#                 st.info("✅ No recent alerts")
# 
#     # ========================================================================
#     # TAB 2: ATHLETE MANAGEMENT
#     # ========================================================================
#     with tab2:
#         st.header("👥 Athlete Registry")
#         col1, col2 = st.columns([1, 2])
# 
#         with col1:
#             st.subheader("➕ Register New Athlete")
#             with st.form("register_form", clear_on_submit=True):
#                 new_name = st.text_input("Athlete Name", key="reg_name")
#                 new_sport = st.selectbox("Sport", ["Football", "Basketball", "Tennis", "Swimming", "Track", "Other"], key="reg_sport")
#                 new_age = st.number_input("Age", 16, 40, 22, key="reg_age")
#                 new_weight = st.number_input("Weight (kg)", 40, 120, 70, key="reg_weight")
#                 submit = st.form_submit_button("✅ Register", key="reg_submit")
# 
#                 if submit and new_name:
#                     add_athlete_to_db(new_name, new_sport, new_age, new_weight)
#                     st.success(f"🎉 {new_name} registered successfully!")
#                     st.rerun()
# 
#         with col2:
#             st.subheader("📋 Registered Athletes")
#             athletes_df = get_athletes_from_db()
#             if not athletes_df.empty:
#                 st.dataframe(athletes_df, use_container_width=True)
# 
#                 if len(athletes_df) > 0:
#                     fig = px.pie(athletes_df, names='sport', title='Athletes by Sport',
#                                color_discrete_sequence=['#8a2be2', '#ff1493', '#00f2fe', '#ffa500', '#00ff88', '#ff6b6b'],
#                                hole=0.4)
#                     fig.update_layout(template='plotly_dark', height=350,
#                                     plot_bgcolor='rgba(0,0,0,0.5)',
#                                     paper_bgcolor='rgba(0,0,0,0.5)',
#                                     font=dict(color='#ffffff'))
#                     st.plotly_chart(fig, use_container_width=True)
# 
#                 st.markdown("---")
#                 st.subheader("🗑️ Delete Athlete")
#                 if not athletes_df.empty:
#                     delete_option = st.selectbox("Select athlete to delete", athletes_df['name'].tolist(), key="delete_athlete")
#                     if st.button("🗑️ Delete Selected"):
#                         athlete_id = athletes_df[athletes_df['name'] == delete_option]['id'].values[0]
#                         delete_athlete_from_db(athlete_id)
#                         st.success(f"✅ {delete_option} deleted!")
#                         st.rerun()
#             else:
#                 st.info("📭 No athletes registered yet. Use the form to add one!")
# 
#     # ========================================================================
#     # TAB 3: KPI INPUT & PREDICTION
#     # ========================================================================
#     with tab3:
#         st.header("⚙️ Real-Time KPI Monitoring & Injury Prediction")
#         col1, col2 = st.columns([1, 2])
# 
#         with col1:
#             st.subheader("📊 Input Biometrics")
#             athletes_df = get_athletes_from_db()
#             athlete_options = athletes_df['name'].tolist() if not athletes_df.empty else []
# 
#             if athlete_options:
#                 player_name = st.selectbox("Select Athlete", athlete_options, key="kpi_athlete")
#             else:
#                 st.warning("⚠️ No athletes registered. Please add athletes in Tab 2 first!")
#                 player_name = "None"
# 
#             selected_model = st.selectbox("🤖 ML Model", ["XGBoost ⭐", "Random Forest", "SVM", "KNN"], key="kpi_model")
# 
#             st.markdown("---")
#             hr = st.number_input("Heart Rate (bpm)", 40, 220, 72, key="kpi_hr")
#             sleep = st.slider("Sleep Hours", 3.0, 12.0, 8.0, key="kpi_sleep")
#             fatigue = st.slider("Fatigue Score (1-10)", 1, 10, 3, key="kpi_fatigue")
#             t_load = st.slider("Training Load", 100, 1000, 500, key="kpi_load")
#             stamina = st.slider("Stamina (%)", 0, 100, 90, key="kpi_stamina")
#             speed = st.number_input("Speed (m/s)", 1.0, 12.0, 6.5, key="kpi_speed")
# 
#             st.markdown("---")
#             if hr < 60:
#                 st.markdown('<div class="status-card status-warning">💓 HR Below normal</div>', unsafe_allow_html=True)
#             elif hr > 100:
#                 st.markdown('<div class="status-card status-error">💓 HR Elevated</div>', unsafe_allow_html=True)
#             else:
#                 st.markdown('<div class="status-card status-success">💓 HR Normal ✅</div>', unsafe_allow_html=True)
# 
#             if sleep < 6:
#                 st.markdown('<div class="status-card status-error">😴 Sleep Insufficient ⚠️</div>', unsafe_allow_html=True)
#             elif sleep < 7:
#                 st.markdown('<div class="status-card status-warning">😴 Sleep Below optimal</div>', unsafe_allow_html=True)
#             else:
#                 st.markdown('<div class="status-card status-success">😴 Sleep Good ✅</div>', unsafe_allow_html=True)
# 
#         with col2:
#             if athlete_options:
#                 st.subheader(f"🎯 Prediction: {player_name}")
#                 m1, m2, m3 = st.columns(3)
#                 m1.metric("⚡ Speed", f"{speed} m/s")
#                 m2.metric("🔋 Stamina", f"{stamina}%")
#                 m3.metric("😫 Fatigue", f"{fatigue}/10")
# 
#                 st.markdown("---")
# 
#                 if st.button("🔮 Run AI Injury Prediction", key="predict_btn"):
#                     with st.spinner("🤖 Analyzing biometrics..."):
#                         time.sleep(0.5)
#                         risk_score = (fatigue * 0.5) + (t_load / 250) - (sleep * 0.3) + (hr / 200)
# 
#                         if risk_score > 4.0 or hr > 185 or (fatigue >= 8 and sleep < 6):
#                             prediction = "🚨 HIGH RISK"
#                             st.error(f"""
#                             **{prediction}**
# 
#                             **Athlete**: {player_name}
#                             **Risk Score**: {risk_score:.2f}
# 
#                             **Recommendation**:
#                             • Immediate rest (24-48h)
#                             • Reduce training intensity
#                             """)
#                         elif risk_score > 2.5:
#                             prediction = "⚠️ MODERATE RISK"
#                             st.warning(f"""
#                             **{prediction}**
# 
#                             **Athlete**: {player_name}
#                             **Risk Score**: {risk_score:.2f}
# 
#                             **Recommendation**:
#                             • Light recovery session
#                             • Ensure 8+ hours sleep
#                             """)
#                         else:
#                             prediction = "✅ LOW RISK"
#                             st.success(f"""
#                             **{prediction}**
# 
#                             **Athlete**: {player_name}
#                             **Risk Score**: {risk_score:.2f}
#                             **Confidence**: {95 - risk_score*5:.1f}%
# 
#                             **Recommendation**:
#                             • Proceed with training
#                             • Maintain hydration
#                             """)
# 
#                         save_kpi_record(player_name, hr, sleep, fatigue, t_load, stamina, speed,
#                                        risk_score, prediction, selected_model)
#                         st.info("💾 Record saved to database!")
#             else:
#                 st.warning("⚠️ No athletes available. Please register athletes in Tab 2 first!")
# 
#     # ========================================================================
#     # TAB 4: ANALYTICS
#     # ========================================================================
#     with tab4:
#         st.header("📊 Model Performance Analytics")
#         st.markdown("*Based on Advanced Research Data*")
# 
#         results = pd.DataFrame({
#             'Model': ['KNN', 'Decision Tree', 'SVM', 'Random Forest', 'XGBoost'],
#             'Recall (Injury Detection)': [0.24, 0.30, 0.50, 0.48, 0.46],
#             'Precision': [0.68, 0.62, 0.71, 0.75, 0.78],
#             'F1-Score': [0.35, 0.41, 0.59, 0.59, 0.58]
#         })
# 
#         col1, col2 = st.columns(2)
# 
#         with col1:
#             st.subheader("🎯 Recall Comparison")
#             fig1 = px.bar(results, x='Model', y='Recall (Injury Detection)',
#                          color='Recall (Injury Detection)',
#                          color_continuous_scale='Purples', text_auto='.2f')
#             fig1.update_layout(template='plotly_dark', height=400,
#                             plot_bgcolor='rgba(0,0,0,0.5)',
#                             paper_bgcolor='rgba(0,0,0,0.5)',
#                             font=dict(color='#ffffff'))
#             st.plotly_chart(fig1, use_container_width=True)
# 
#         with col2:
#             st.subheader("⚖️ Precision vs Recall")
#             fig2 = px.scatter(results, x='Recall (Injury Detection)', y='Precision',
#                            size='F1-Score', color='Model', text='Model',
#                            color_discrete_sequence=['#00f2fe', '#8a2be2', '#ff1493', '#ffa500', '#00ff88'])
#             fig2.update_layout(template='plotly_dark', height=400,
#                             plot_bgcolor='rgba(0,0,0,0.5)',
#                             paper_bgcolor='rgba(0,0,0,0.5)',
#                             font=dict(color='#ffffff'))
#             st.plotly_chart(fig2, use_container_width=True)
# 
#         st.markdown("---")
#         st.subheader("📈 Your Research Data Statistics")
#         kpi_df = get_kpi_records()
#         if not kpi_df.empty:
#             col1, col2, col3, col4 = st.columns(4)
#             with col1:
#                 st.metric("Total Records", len(kpi_df))
#             with col2:
#                 st.metric("Avg Risk Score", round(kpi_df['risk_score'].mean(), 2))
#             with col3:
#                 st.metric("High Risk Count", len(kpi_df[kpi_df['prediction'].str.contains('HIGH')]))
#             with col4:
#                 st.metric("Last Updated", kpi_df['timestamp'].iloc[-1].split()[0])
# 
#             st.markdown("---")
#             st.subheader("📊 Recent KPI Records")
#             st.dataframe(kpi_df.head(10), use_container_width=True)
#         else:
#             st.info("📭 No KPI records yet. Add predictions in Tab 3!")
# 
#     # ========================================================================
#     # TAB 5: DATABASE MANAGEMENT
#     # ========================================================================
#     with tab5:
#         st.header("💾 Database Management")
# 
#         col1, col2 = st.columns(2)
# 
#         with col1:
#             st.subheader("📊 Database Statistics")
# 
#             athlete_count = get_athlete_count()
#             kpi_count = get_total_kpi_records()
# 
#             st.metric("Total Athletes", athlete_count)
#             st.metric("Total KPI Records", kpi_count)
# 
#             if os.path.exists(DB_FILE):
#                 db_size = os.path.getsize(DB_FILE) / 1024
#                 st.metric("Database Size", f"{db_size:.2f} KB")
# 
#             st.markdown("---")
#             st.subheader("📥 Export Data")
# 
#             athletes_df = get_athletes_from_db()
#             kpi_df = get_kpi_records()
# 
#             if not athletes_df.empty:
#                 csv_athletes = athletes_df.to_csv(index=False)
#                 st.download_button(
#                     "📥 Download Athletes (CSV)",
#                     csv_athletes,
#                     f"athletes_{datetime.now().strftime('%Y%m%d')}.csv",
#                     "text/csv",
#                     key='download_athletes'
#                 )
# 
#             if not kpi_df.empty:
#                 csv_kpi = kpi_df.to_csv(index=False)
#                 st.download_button(
#                     "📥 Download KPI Records (CSV)",
#                     csv_kpi,
#                     f"kpi_records_{datetime.now().strftime('%Y%m%d')}.csv",
#                     "text/csv",
#                     key='download_kpi'
#                 )
# 
#         with col2:
#             st.subheader("⚠️ Database Operations")
# 
#             if st.button("🗑️ Clear All KPI Records", key="clear_kpi"):
#                 conn = sqlite3.connect(DB_FILE)
#                 cursor = conn.cursor()
#                 cursor.execute("DELETE FROM kpi_records")
#                 conn.commit()
#                 conn.close()
#                 st.success("✅ All KPI records deleted!")
#                 st.rerun()
# 
#             if st.button("🗑️ Clear All Athletes", key="clear_athletes"):
#                 conn = sqlite3.connect(DB_FILE)
#                 cursor = conn.cursor()
#                 cursor.execute("DELETE FROM athletes")
#                 conn.commit()
#                 conn.close()
#                 st.success("✅ All athletes deleted!")
#                 st.rerun()
# 
#             st.markdown("---")
#             st.subheader("ℹ️ Database Info")
#             st.info(f"""
#             **Database File**: {DB_FILE}
#             **Location**: Current directory
#             **Created**: {datetime.fromtimestamp(os.path.getctime(DB_FILE)).strftime('%Y-%m-%d %H:%M') if os.path.exists(DB_FILE) else 'N/A'}
#             **Last Modified**: {datetime.fromtimestamp(os.path.getmtime(DB_FILE)).strftime('%Y-%m-%d %H:%M') if os.path.exists(DB_FILE) else 'N/A'}
#             """)
# 
#     st.markdown('</div>', unsafe_allow_html=True)
#     st.markdown('<div class="footer">🏅 AI Sports Performance Monitoring System | © 2024 | All Rights Reserved</div>', unsafe_allow_html=True)
# 
# # ============================================================================
# # 🚀 MAIN
# # ============================================================================
# def main():
#     if not st.session_state['logged_in']:
#         login_page()
#     else:
#         dashboard()
# 
# if __name__ == "__main__":
#     main()

# Install Streamlit
!pip install streamlit -q

# Install localtunnel to expose the dashboard to a public URL
!npm install -g localtunnel

import joblib

# Save the trained SVM model
joblib.dump(svm_model, 'svm_model.pkl')

# Save the trained KNN model
joblib.dump(knn_model, 'knn_model.pkl')

# The Streamlit app expects 'Random Forest'. Since dt_pruned_model (Decision Tree) is trained,
# it can be used as a placeholder for 'Random Forest' for the dashboard demonstration.
joblib.dump(dt_pruned_model, 'rf_model.pkl')

# xgb_model is not defined in the notebook. If you have an XGBoost model,
# define and train it, then uncomment the line below to save it.
# joblib.dump(xgb_model, 'xgb_model.pkl')

# 1. Manually install ngrok to bypass the Forbidden/Installation error
!curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
!echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
!sudo apt update -q
!sudo apt install ngrok -q

# 2. Add your authtoken
# This assumes your authtoken is correct and already added to ngrok config.
# If you face 'ERR_NGROK_4018' (invalid authtoken), ensure the token is valid and re-run this cell.
!ngrok config add-authtoken 3BiIXbQOZXxSztgHCA9kCbEqWwy_4hPpVAyvpqoPknCc2RdJG

# 3. Stop any existing streamlit or ngrok sessions
!pkill -f streamlit || true
!pkill -f ngrok || true

!pkill streamlit
!pkill npx

!pip install streamlit -q

!pip install pyngrok

# Download the official ngrok linux binary
!wget -q https://bin.ngrok.com/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
# Extract it
!tar -xvzf ngrok-v3-stable-linux-amd64.tgz
# Move it to a folder in your path
!mv ngrok /usr/local/bin/

import os
import time
import subprocess
import json
import urllib.request
from urllib.error import URLError

# Define the NGROK_TOKEN
NGROK_TOKEN = "3BiIXbQOZXxSztgHCA9kCbEqWwy_4hPpVAyvpqoPknCc2RdJG" # Replace with your actual ngrok authtoken

# Ensure previous ngrok processes are truly terminated
subprocess.run(['pkill', '-f', 'ngrok'], check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# 1. Start Streamlit
streamlit_process = subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

# 2. Start ngrok, capturing stdout and stderr
# Explicitly pass the authtoken to ensure ngrok is authenticated.
ngrok_process = subprocess.Popen(
    ["ngrok", "http", "8501", "--authtoken", NGROK_TOKEN], # Added --authtoken
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# 3. Wait for the ngrok API to become available
ngrok_api_url = "http://localhost:4040/api/tunnels"
max_retries = 20 # Increased retries
print("Waiting for ngrok API...")
for i in range(max_retries):
    try:
        with urllib.request.urlopen(ngrok_api_url, timeout=1) as response:
            print(f"Ngrok API available after {i+1} retries.")
            break
    except URLError:
        # Check if ngrok process terminated early
        if ngrok_process.poll() is not None:
            stderr_output = ngrok_process.stderr.read().decode()
            print(f"❌ Ngrok process terminated unexpectedly with code {ngrok_process.returncode}.")
            print(f"Ngrok stderr: {stderr_output}")
            # Attempt to terminate the streamlit process as well
            streamlit_process.terminate()
            raise Exception(f"Ngrok failed to start: {stderr_output}")
        time.sleep(2) # Wait 2 seconds between retries
else:
    print("❌ Ngrok API did not become available within the timeout.")
    stderr_output = ngrok_process.stderr.read().decode()
    print(f"Ngrok stderr (after timeout): {stderr_output}")
    # Attempt to terminate processes
    ngrok_process.terminate()
    streamlit_process.terminate()
    raise Exception("Ngrok API not accessible within timeout.")

# 4. Grab the URL from the local ngrok API
try:
    with urllib.request.urlopen(ngrok_api_url) as response:
        data = json.loads(response.read().decode())
        public_url = data['tunnels'][0]['public_url']
        print(f"\n🚀 Streamlit is live at: {public_url}")
except Exception as e:
    print(f"\n❌ Could not fetch the URL. Make sure ngrok is running and authenticated. Error: {e}")
    # Attempt to terminate processes
    ngrok_process.terminate()
    streamlit_process.terminate()

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# plotly